apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::238004439629:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BUAZBA4G6WH8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::238004439629:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T22:23:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1632"
  uid: d67147e6-1a64-4eb5-8949-0dbf7d3ff796
