apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::619908637995:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-TOTKVCGXQO5E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::619908637995:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T11:44:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1739"
  uid: 7ed9562e-aef6-4a37-ac78-7683a86ed10b
